Docs: uploaded and added docker section images
harness-community/cd-pipeline-sample pull request #13
Opened 2022-10-05 04:50 UTC by rkapoor10

Files modified 
 - connectors -> DockerHub.md
 - secrets -> GithubPAT.md

2022-10-05 08:26 UTC, Ompragash requested changes
Great @rkapoor10! Added minor improvements, rest looks good

2022-10-05 08:26 UTC, Ompragash commented on docs/connectors/DockerHub.md
>  Follow these step to set up a Docker Connector
```suggestion
Follow these steps to set up a Docker Connector
```

2022-10-05 08:53 UTC, rkapoor10 commented on docs/connectors/DockerHub.md
>  Follow these step to set up a Docker Connector
done

2022-10-06 12:31 UTC, Ompragash approved these changes
LGTM! Thanks @rkapoor10

2022-10-06 12:31 UTC, merged